CREATE DATABASE QuanLiDiemThi;
USE QuanliDiemThi;
CREATE TABLE hocsinh(
maHS VARCHAR(20) PRIMARY KEY,
TenHS VARCHAR(50),
ngaysinh DATETIME,
lop VARCHAR(20),
gt VARCHAR(20)
);
CREATE TABLE monhoc(
MaMH VARCHAR(20) PRIMARY KEY,
TenMH VARCHAR(50)
);
CREATE TABLE bangdiem(
MaHS VARCHAR(20),
MaMH VARCHAR(20),
DiemThi INT,
NgayKT DATETIME,
PRIMARY KEY (MaHS,MaMH),
FOREIGN KEY (MaHS) REFERENCES hocsinh (MaHS),
FOREIGN KEY (MaMH) REFERENCES monhoc (MaMH)
);
CREATE TABLE giaovien(
MaGV VARCHAR(20) PRIMARY KEY,
TenGV VARCHAR(20),
SDT VARCHAR(10)
);
ALTER TABLE monhoc add MaGV VARCHAR(20);
ALTER TABLE monhoc ADD constraint fk_MaGV foreign key (MaGV) references giaovien ( MaGV);

